# Google Cloud Build configuration for single Cloud Run deployment
steps:
  # Build the unified Docker image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_AZURE_CLIENT_ID=${_AZURE_CLIENT_ID}'
      - '--build-arg'
      - 'REACT_APP_AZURE_TENANT_ID=${_AZURE_TENANT_ID}'
      - '--build-arg'
      - 'REACT_APP_REDIRECT_URI=${_REDIRECT_URI}'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/excom-ai:latest'
      - '-f'
      - 'Dockerfile'
      - '.'

  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/excom-ai'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'excom-ai'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/excom-ai:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '8000'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--set-secrets'
      - 'ANTHROPIC_API_KEY=anthropic-api-key:latest'
      - '--set-secrets'
      - 'JIRA_API_TOKEN=jira-api-token:latest'
      - '--set-secrets'
      - 'JIRA_EMAIL=jira-email:latest'
      - '--set-secrets'
      - 'JIRA_SERVER=jira-server:latest'
      - '--set-secrets'
      - 'FRESHSERVICE_DOMAIN=freshservice-domain:latest'
      - '--set-secrets'
      - 'FRESHSERVICE_API_KEY=freshservice-api-key:latest'
      - '--set-env-vars'
      - 'JIRA_JQL=${_JIRA_JQL}'
      - '--set-env-vars'
      - 'LANGCHAIN_TRACING_V2=${_LANGCHAIN_TRACING_V2}'

# Substitution variables with defaults
substitutions:
  _REGION: 'us-central1'
  _MIN_INSTANCES: '1'
  _MAX_INSTANCES: '100'
  _MEMORY: '1Gi'
  _CPU: '1'
  _AZURE_CLIENT_ID: '${REACT_APP_AZURE_CLIENT_ID}'
  _AZURE_TENANT_ID: '${REACT_APP_AZURE_TENANT_ID}'
  _REDIRECT_URI: 'https://YOUR-CLOUD-RUN-URL.run.app'
  _JIRA_JQL: 'PROJECT = "DMD" AND type = epic'
  _LANGCHAIN_TRACING_V2: 'false'

# Build timeout
timeout: '1200s'

# Images to be pushed to Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docker-repo/excom-ai:latest'