services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: excom-ai-backend
    ports:
      - "9000:9000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - JIRA_SERVER=${JIRA_SERVER}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - JIRA_JQL=${JIRA_JQL}
      - FRESHSERVICE_DOMAIN=${FRESHSERVICE_DOMAIN}
      - FRESHSERVICE_API_KEY=${FRESHSERVICE_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - excom-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - REACT_APP_AZURE_CLIENT_ID=${REACT_APP_AZURE_CLIENT_ID}
        - REACT_APP_AZURE_TENANT_ID=${REACT_APP_AZURE_TENANT_ID}
        - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI:-http://localhost:8000}
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:9000}
    container_name: excom-ai-frontend
    ports:
      - "8000:3000"
    depends_on:
      - backend
    networks:
      - excom-network
    restart: unless-stopped

networks:
  excom-network:
    driver: bridge